In [1]:
import tensorflow as tf
from tensorflow import keras

In [2]:
import tensorflow as tf

# Define the custom loss function
def root_mean_squared_error(y_true, y_pred):
    return tf.sqrt(tf.reduce_mean(tf.square(y_pred - y_true)))

# Load the model with custom loss function
model = tf.keras.models.load_model('my_litecoinLSTM_model.h5', custom_objects={'root_mean_squared_error': root_mean_squared_error})


In [3]:
model.summary()


Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_4 (LSTM)               (None, 1, 480)            935040    
                                                                 
 dropout_2 (Dropout)         (None, 1, 480)            0         
                                                                 
 lstm_5 (LSTM)               (None, 64)                139520    
                                                                 
 dense_2 (Dense)             (None, 1)                 65        
                                                                 
Total params: 1,074,625
Trainable params: 1,074,625
Non-trainable params: 0
_________________________________________________________________


# GET LITECOIN DATA 

In [4]:
import pandas as pd
import requests

import datetime

import datetime

# Get the current date
current_date = datetime.datetime.now()

# Calculate the previous day
previous_day = current_date - datetime.timedelta(days=1)
previous_day_start = datetime.datetime(previous_day.year, previous_day.month, previous_day.day, 0, 0, 0)
previous_day_end = previous_day_start + datetime.timedelta(days=1)

# Convert the timestamps to milliseconds
start_time = int(previous_day_start.timestamp()) * 1000
end_time = int(previous_day_end.timestamp()) * 1000

# Construct the URL with the modified timestamp
url = f"https://api.binance.com/api/v3/klines?symbol=LTCUSDT&interval=1d&startTime={start_time}&endTime={end_time}&limit=1"



# Send GET request to the API
response = requests.get(url)

# Parse the response JSON data
data = response.json()

# Define column names
columns = ['date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Close Time', 'Quote Asset Volume', 'Number of Trades', 'TB Base Volume', 'Taker Buy Quote Asset Volume', 'Ignore']

# Create DataFrame
ltc = pd.DataFrame(data, columns=columns)

# Convert data types
ltc['date'] = pd.to_datetime(ltc['date'], unit='ms')
ltc[['Open', 'High', 'Low', 'Close', 'Volume', 'Close Time', 'Quote Asset Volume', 'Number of Trades', 'TB Base Volume', 'Taker Buy Quote Asset Volume', 'Ignore']] = ltc[['Open', 'High', 'Low', 'Close', 'Volume', 'Close Time', 'Quote Asset Volume', 'Number of Trades', 'TB Base Volume', 'Taker Buy Quote Asset Volume', 'Ignore']].astype(float)

# Print DataFrame
print(ltc)


        date   Open   High    Low  Close      Volume    Close Time  \
0 2023-05-29  91.46  92.18  90.12  90.86  484868.109  1.685405e+12   

   Quote Asset Volume  Number of Trades  TB Base Volume  \
0        4.420683e+07          103965.0       243362.13   

   Taker Buy Quote Asset Volume  Ignore  
0                  2.219324e+07     0.0  


In [5]:
ltc.drop(['Quote Asset Volume','Taker Buy Quote Asset Volume','Close Time','Ignore','Volume','Number of Trades',
          'TB Base Volume'
         ],axis=1,inplace=True)


In [6]:
ltc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype         
---  ------  --------------  -----         
 0   date    1 non-null      datetime64[ns]
 1   Open    1 non-null      float64       
 2   High    1 non-null      float64       
 3   Low     1 non-null      float64       
 4   Close   1 non-null      float64       
dtypes: datetime64[ns](1), float64(4)
memory usage: 168.0 bytes


In [7]:
ltc['close_nextday']=90

In [8]:
# import requests

# url = 'https://min-api.cryptocompare.com/data/blockchain/histo/day'
# params = {'fsym': 'LTC', 'limit': 2, 'api_key': 'e6a9a2c327eba343b8ba318f86017574f6d9bdb9d5d13ae643531bda926f5e32'}

# response = requests.get(url, params=params)

# if response.status_code != 200:
#     print(f'Request failed with status code {response.status_code}.')
# else:
#     data = response.json()['Data']
#     print(data)


In [9]:
import requests
import datetime

# Calculate the previous day
previous_day = datetime.date.today() - datetime.timedelta(days=1)

# Format the previous day in the required format (YYYY-MM-DD)
previous_day_str = previous_day.strftime('%Y-%m-%d')

# Construct the URL with the modified date
url = f'https://api.blockchair.com/litecoin/stats?date={previous_day_str}'

# Send the request and check the response
response = requests.get(url)

if response.status_code != 200:
    print(f'Request failed with status code {response.status_code}.')
else:
    data = response.json()
    blockchain_data = data['data']
    print(blockchain_data)


{'blocks': 2482807, 'transactions': 161851363, 'outputs': 512570790, 'circulation': 7303313323347135, 'blocks_24h': 586, 'transactions_24h': 242056, 'difficulty': 25122123.350546, 'volume_24h': 4404267082775050, 'mempool_transactions': 163, 'mempool_size': 152968, 'mempool_tps': 1.4833333333333334, 'mempool_total_fee_usd': 0.9373, 'best_block_height': 2482806, 'best_block_hash': '4d69bc42d5e36e70501fca8f0590b098496f43a5ce0e9da2d3dcc8a96fbf3c08', 'best_block_time': '2023-05-30 08:15:07', 'blockchain_size': 103069379744, 'average_transaction_fee_24h': 5884, 'inflation_24h': 732500000000, 'median_transaction_fee_24h': 492, 'cdd_24h': 21985158.238884695, 'mempool_outputs': 1271, 'largest_transaction_24h': {'hash': 'e63b547b863bb59ba331b718a8bbc80ca8c6cb0499514cc8c29a7fe492968d1b', 'value_usd': 14449485}, 'nodes': 1006, 'hashrate_24h': '734004739395166', 'inflation_usd_24h': 668919, 'average_transaction_fee_usd_24h': 0.00537339762572793, 'median_transaction_fee_usd_24h': 0.0004492944, 'mark

In [10]:
from datetime import datetime, timedelta

hashrate = blockchain_data['hashrate_24h']
difficulty = blockchain_data['difficulty']
previous_day = datetime.today().date() - timedelta(days=1)

# Create dataframe
blockchain_ltc = pd.DataFrame({
    'hashrate': [hashrate],
    'difficulty': [difficulty],

    'date':pd.to_datetime(previous_day)    
})

In [11]:
blockchain_ltc

hashrate    difficulty       date
0  734004739395166  2.512212e+07 2023-05-29

In [12]:
ltc_df = pd.merge(blockchain_ltc,ltc , on=['date'])
print(ltc_df)

          hashrate    difficulty       date   Open   High    Low  Close  \
0  734004739395166  2.512212e+07 2023-05-29  91.46  92.18  90.12  90.86   

   close_nextday  
0             90  


In [13]:
ltc_df.set_index('date', inplace=True)
ltc_df.head()

hashrate    difficulty   Open   High    Low  Close  \
date                                                                    
2023-05-29  734004739395166  2.512212e+07  91.46  92.18  90.12  90.86   

            close_nextday  
date                       
2023-05-29             90

In [14]:
ltc_df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1 entries, 2023-05-29 to 2023-05-29
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   hashrate       1 non-null      object 
 1   difficulty     1 non-null      float64
 2   Open           1 non-null      float64
 3   High           1 non-null      float64
 4   Low            1 non-null      float64
 5   Close          1 non-null      float64
 6   close_nextday  1 non-null      int64  
dtypes: float64(5), int64(1), object(1)
memory usage: 64.0+ bytes


In [15]:
import pickle

# Load the scaler object from the file
with open('LTCscaler.pkl', 'rb') as file:
    scaler = pickle.load(file)

# Use the scaler object as needed
ltc_scaled = scaler.transform(ltc_df)

In [16]:
ltc_scaled

array([[9.23174629e+11, 9.81469634e-01, 1.87546270e-01, 1.75557437e-01,
        2.10115284e-01, 1.85841193e-01, 1.83483220e-01]])

In [23]:
ltc_scaled=ltc_scaled[:,:6]

In [24]:
ltc_scaled

array([[9.23174629e+11, 9.81469634e-01, 1.87546270e-01, 1.75557437e-01,
        2.10115284e-01, 1.85841193e-01]])

In [25]:
input_data_reshaped = tf.expand_dims(ltc_scaled, axis=1)

In [26]:
input_data_reshaped.shape

TensorShape([1, 1, 6])

In [27]:
input_data_reshaped

<tf.Tensor: shape=(1, 1, 6), dtype=float64, numpy=
array([[[9.23174629e+11, 9.81469634e-01, 1.87546270e-01, 1.75557437e-01,
         2.10115284e-01, 1.85841193e-01]]])>

In [28]:
predictions=model.predict (input_data_reshaped)

1/1 [==============================] - 1s 1s/step


In [29]:
predictions[-1][0]

0.62035865

In [31]:
import pickle

# Load the scaler object from the file
with open('litecoin_closemin.pkl', 'rb') as file:
    close_nextdaymin = pickle.load(file)

print(close_nextdaymin)

23.08


In [32]:
import pickle

# Load the scaler object from the file
with open('litecoin_closemax.pkl', 'rb') as file:
    close_nextdaymax = pickle.load(file)

print(close_nextdaymax)

387.8


In [33]:
# denormalized_value = (normalized_value * (max_value - min_value)) + min_value
denormalized_value =  (abs(predictions[-1][0] ) * (close_nextdaymax - close_nextdaymin)+ close_nextdaymin)
display(denormalized_value)

249.3372053384781

In [ ]:
# !pip install nbconvert


In [ ]:
# from nbconvert import PythonExporter

# def convert_notebook_to_script(notebook_path, script_path):
#     exporter = PythonExporter()
#     exporter.exclude_input_prompt = True  # Exclude input prompts in the script
#     output, _ = exporter.from_file(notebook_path)
#     with open(script_path, 'w', encoding='utf-8') as f:
#         f.write(output)

# convert_notebook_to_script('PredictNewData.ipynb', 'PredictNewData.py')


In [ ]:
# import pandas as pd
# import requests

# # Example data
# url = 'https://api.binance.com/api/v3/klines?symbol=BTCUSDT&interval=1d&limit=1'

# # Send GET request to the API
# response = requests.get(url)

# # Parse the response JSON data
# data = response.json()

# # Define column names
# columns = ['Open Time', 'Open', 'High', 'Low', 'Close', 'Volume', 'Close Time', 'Quote Asset Volume', 'Number of Trades', 'TB Base Volume', 'Taker Buy Quote Asset Volume', 'Ignore']

# # Create DataFrame
# btc = pd.DataFrame(data, columns=columns)

# # Convert data types
# btc['Open Time'] = pd.to_datetime(btc['Open Time'], unit='ms')
# btc[['Open', 'High', 'Low', 'Close', 'Volume', 'Close Time', 'Quote Asset Volume', 'Number of Trades', 'TB Base Volume', 'Taker Buy Quote Asset Volume', 'Ignore']] = df[['Open', 'High', 'Low', 'Close', 'Volume', 'Close Time', 'Quote Asset Volume', 'Number of Trades', 'Taker Buy Base Asset Volume', 'Taker Buy Quote Asset Volume', 'Ignore']].astype(float)

# # Print DataFrame
# print(btc)


In [ ]:
# btc.drop(['Quote Asset Volume','Taker Buy Quote Asset Volume','Close Time','Ignore'],axis=1,inplace=True)


In [ ]:
# btc

In [ ]:
# ###this is the one that works 
# import warnings
# from datetime import datetime

# # Ignore FutureWarning messages
# warnings.filterwarnings("ignore", category=FutureWarning)
# url = 'https://api.blockchain.info/charts'
# params = {
#     'timespan': '1days',
#     'format': 'json'
# }

# # Define the data to retrieve
# data_types = [ 'market-price', 'difficulty' , 'total-bitcoins',
#               'blocks-size', 'miners-revenue',"market-cap"]
# #data_types=features

# # Initialize a dictionary to store the dataframes
# dfs = {}

# # Loop over the data types and retrieve the data
# for data_type in data_types:
#     # Set the API endpoint for the current data type
#     current_url = f"{url}/{data_type}"
    
#     # Make the API request
#     response = requests.get(current_url, params=params)
    
#     # Extract the data from the response
#     data = response.json()['values']
    
#     # Create an empty dataframe for the current data type
#     df = pd.DataFrame(columns=['date', data_type])
    
#     # Process the data
#     for entry in data:
#         # Convert the timestamp to a datetime object
#         date = datetime.fromtimestamp(entry['x']).date()
        
#         # Add a new row to the DataFrame
#         df = df.append({'date': date, data_type: entry['y']}, ignore_index=True)
    
#     # Store the DataFrame in the dictionary
#     dfs[data_type] = df

# # Print the DataFrames
# for data_type, df in dfs.items():
#     print(f"{data_type}:")
#     print(df)
#     print("\n")



In [ ]:
# type(dfs)

In [ ]:
# #list of dataframes; each with the blockchain data
# frames=[]
# for key in dfs.keys():
#     name=key.replace('-','')
#     name=dfs[key]
#     frames.append(name)
# frames[4]

In [ ]:
# #MERGE ALL RESULTING DATAFRAMES 
# merged_df=frames[0].merge(frames[1],on='date')
# print(merged_df)
# for i in range(1,len(frames)-1):
#     merged_df=merged_df.merge(frames[i+1],on='date')
#     print(merged_df)

In [ ]:
# t1=btc.set_index('Open Time')
# t1.head()
# type(btc['Open Time'][0])

In [ ]:
# #you must merge based on the date; normal index will lead to false results because of how you took a sample of the data
# t2=temp_df.set_index('date')
# t2.head()
# type(temp_df['date'])

In [ ]:
# mergedData_df=t1.merge(t2,on='date')